FROM python:3.11.6
RUN apt-get update \
    && apt-get install -y \
    nginx

WORKDIR /usr/src/app
COPY . /usr/src/app

RUN pip install --upgrade --force-reinstall pip && pip install -r /usr/src/app/requirements.txt

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]